// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDWOvUBtFcHoNDQDuP9G0yLtOiMtsRN_Pw',
    appId: '1:1026903577783:web:d36eba6e811bf868efe932',
    messagingSenderId: '1026903577783',
    projectId: 'finbrain-bb12c',
    authDomain: 'finbrain-bb12c.firebaseapp.com',
    storageBucket: 'finbrain-bb12c.firebasestorage.app',
    measurementId: 'G-5EKPD2PK1N',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCLy7diKtVMy3TXiTgEhmq8VIqlMjqgk6s',
    appId: '1:1026903577783:android:7462693cc70bea88efe932',
    messagingSenderId: '1026903577783',
    projectId: 'finbrain-bb12c',
    storageBucket: 'finbrain-bb12c.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCz5V-s3a4yrBd9GVBLBN4eMXRObuDNbNQ',
    appId: '1:1026903577783:ios:b4ad892319825df7efe932',
    messagingSenderId: '1026903577783',
    projectId: 'finbrain-bb12c',
    storageBucket: 'finbrain-bb12c.firebasestorage.app',
    androidClientId: '1026903577783-72eph0ts1b1sor46jaf0c0ui7bf0ukrb.apps.googleusercontent.com',
    iosClientId: '1026903577783-mriqarinnfmij4mac3nhfeqs0bgihf39.apps.googleusercontent.com',
    iosBundleId: 'com.example.finbrain',
  );
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCz5V-s3a4yrBd9GVBLBN4eMXRObuDNbNQ',
    appId: '1:1026903577783:ios:b4ad892319825df7efe932',
    messagingSenderId: '1026903577783',
    projectId: 'finbrain-bb12c',
    storageBucket: 'finbrain-bb12c.firebasestorage.app',
    androidClientId: '1026903577783-72eph0ts1b1sor46jaf0c0ui7bf0ukrb.apps.googleusercontent.com',
    iosClientId: '1026903577783-mriqarinnfmij4mac3nhfeqs0bgihf39.apps.googleusercontent.com',
    iosBundleId: 'com.example.finbrain',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDWOvUBtFcHoNDQDuP9G0yLtOiMtsRN_Pw',
    appId: '1:1026903577783:web:83db8b98b66353beefe932',
    messagingSenderId: '1026903577783',
    projectId: 'finbrain-bb12c',
    authDomain: 'finbrain-bb12c.firebaseapp.com',
    storageBucket: 'finbrain-bb12c.firebasestorage.app',
    measurementId: 'G-HR5LLSKZBX',
  );
}
